// frontend/product-app-react-demo6-routers/src/App.tsx
import React from 'react';
import './App.css';
import ProductsList from './components/ProductList';
import { ProductProvider } from './context/productContext';
import { Link } from 'react-router-dom';
import {FC} from 'react';

const App :FC<any> = ({children}) => {
  return (
    // There should exist at least one root element , otherwise you aren't able to 
    // render the given component.  
    // That's why we add empty JSX tages.

    // JSX is down below.
    <>
      {/* <div className='container productsContainer'>
        <ProductProvider url ="http://localhost:4200">
            <ProductsList />
        </ProductProvider>
      </div> */}

      <nav className="navbar navbar-expand-lg bg-body-tertiary">
        <div className="container-fluid">
          <a className="navbar-brand" href="#">Navbar</a>
          <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>

          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav me-auto mb-2 mb-lg-0">
              
              <li className="nav-item">
                <Link className="nav-link active" aria-current="page" to="/">Home</Link>
              </li>

              <li className="nav-item">
                <Link className="nav-link active" aria-current="page" to="/products">ProductsList</Link>
              </li>
            </ul>

            <form className="d-flex" role="search">
              <input className="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
              <button className="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      <div className='container'>
        {/* This is the place or placeholer where the router components will be rendered. */}
         {children}
      </div>

      <footer className='mt-5 p-3 text-center bg-light'>
        Products @copy;
      </footer>
    </>
  );
}

export default App;

// frontend/product-app-ng-demo3-spa/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'product-app-ng-demo2';
}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" routerLink="/">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" routerLink="/products">ProductsList</a>
          </li>
        </ul>

        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" value=""/>
            <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      </div>
    </div>
  </nav>

  <div class='container'>
    <!-- Router-outlet is responsible for rendering all the children -->
    <router-outlet>

    </router-outlet>
  </div>

  <footer class='mt-5 p-3 text-center bg-light'>
    IBM India Pvt Ltd
  </footer>
